export const PRODUCTS = [
    {
        id: 1,
        cat: "CCTV",
        brand: "Hikvision",
        name: "Hikvision DS-2CD2143G2-I AcuSense 4MP Fixed Dome",
        price: 48500,
        oldPrice: 56000,
        rating: 4.8,
        reviews: 24,
        badge: "Best Seller",
        sku: "HIK-DS2CD2143G2",
        tags: ["4MP", "IR 40m", "IP67", "H.265+"],
        image: "/products/HD Cameras Installer Orange County.jpeg"
    },
    {
        id: 2,
        cat: "CCTV",
        brand: "Dahua",
        name: "Dahua IPC-HDW2849H-S-IL 8MP Full-color Eyeball Camera",
        price: 62000,
        oldPrice: null,
        rating: 4.7,
        reviews: 18,
        badge: "New",
        sku: "DAH-HDWF2849H",
        tags: ["8MP", "Full Color", "AI", "IP67"],
        // image: "#"
    },
    {
        id: 3,
        cat: "Access Control",
        brand: "ZKTeco",
        name: "ZKTeco SF300 Fingerprint & RFID Door Access Reader",
        price: 34500,
        oldPrice: 40000,
        rating: 4.6,
        reviews: 32,
        badge: null,
        sku: "ZKT-SF300",
        tags: ["Fingerprint", "RFID", "Standalone"],
        // image: "#"
    },
    {
        id: 4,
        cat: "Networking",
        brand: "Cisco",
        name: "Cisco CBS350-24T-4G Managed 24-Port Gigabit Switch",
        price: 285000,
        oldPrice: null,
        rating: 4.9,
        reviews: 12,
        badge: "Enterprise Pick",
        sku: "CSC-CBS35024T",
        tags: ["24-Port", "PoE", "Layer 3", "Managed"],
        // image: "#"
    },
    {
        id: 5,
        cat: "Fiber Optic",
        brand: "Corning",
        name: "Corning SMF-28 Ultra Single-Mode Fiber Cable (Per Metre)",
        price: 450,
        oldPrice: 520,
        rating: 4.9,
        reviews: 56,
        badge: null,
        sku: "COR-SMF28U-M",
        tags: ["Single-Mode", "OS2", "LSZH", "Per Metre"],
        // image: "#"
    },
    {
        id: 6,
        cat: "CCTV",
        brand: "Axis",
        name: "Axis P3245-V Fixed Dome Camera with ARTPEC-7",
        price: 195000,
        oldPrice: null,
        rating: 4.8,
        reviews: 9,
        badge: "Premium",
        sku: "AXS-P3245V",
        tags: ["2MP", "WDR", "ARTPEC-7", "IK10"],
        // image: "#"
    },
    {
        id: 7,
        cat: "Access Control",
        brand: "HID",
        name: "HID VertX EVO V1000 Network Door Controller",
        price: 128000,
        oldPrice: 145000,
        rating: 4.7,
        reviews: 7,
        badge: null,
        sku: "HID-V1000",
        tags: ["4-Door", "Network", "OSDP", "HID"],
        // image: "#"
    },
    {
        id: 8,
        cat: "Networking",
        brand: "Ubiquiti",
        name: "Ubiquiti UniFi U6 Pro WiFi 6 Access Point",
        price: 89000,
        oldPrice: null,
        rating: 4.8,
        reviews: 44,
        badge: "Popular",
        sku: "UBQ-U6PRO",
        tags: ["WiFi 6", "4x4 MU-MIMO", "PoE", "Indoor"],
        // image: "#"
    },
    {
        id: 9,
        cat: "Fiber Optic",
        brand: "AFL",
        name: "AFL Fujikura 90S+ Fusion Splicer Kit",
        price: 1250000,
        oldPrice: null,
        rating: 4.9,
        reviews: 6,
        badge: "Pro Grade",
        sku: "AFL-90SPLUS",
        tags: ["Core Alignment", "5s Splice", "Auto Mode"],
        // image: "#"
    },
];

export const CATEGORIES = ["All Products", "CCTV", "Access Control", "Networking", "Fiber Optic"];

export type Product = (typeof PRODUCTS)[number];
