export const CATEGORIES = ["All Topics", "Surveillance", "Fiber Optic", "ICT Infrastructure", "Access Control", "Industrial Safety", "Industry News"];

export const POSTS = [
    { id: 1, cat: "Surveillance", title: "How to Choose the Right CCTV System for a Warehouse in 2025", excerpt: "Warehouses pose unique surveillance challenges — high ceilings, low light, large open areas, and multiple entry points. Here's how to architect the right solution.", author: "Babatunde Adewale", date: "Feb 18, 2025", read: "6 min", featured: true, tags: ["CCTV", "Warehousing", "IP Cameras"] },
    { id: 2, cat: "Fiber Optic", title: "Fiber vs. Copper: What Nigerian Enterprises Need to Know in 2025", excerpt: "The case for fiber has never been stronger — but legacy copper still dominates many Nigerian enterprise networks. We break down the real cost of staying behind.", author: "Ngozi Okafor", date: "Feb 5, 2025", read: "8 min", featured: true, tags: ["Fiber Optic", "Networking", "Enterprise IT"] },
    { id: 3, cat: "ICT Infrastructure", title: "Building a Resilient Office Network: A Practical Guide for Lagos Businesses", excerpt: "From structured cabling to managed WiFi — the building blocks of a network that doesn't let you down during Nigeria's most demanding business days.", author: "Amaka Nweze", date: "Jan 22, 2025", read: "7 min", featured: true, tags: ["Networking", "LAN/WAN", "Lagos"] },
    { id: 4, cat: "Access Control", title: "Biometric vs. RFID Access Control: Which Is Right for Your Business?", excerpt: "Both systems have clear strengths. The right choice depends on your threat model, budget, and how many people you're controlling access for.", author: "Babatunde Adewale", date: "Jan 10, 2025", read: "5 min", featured: false, tags: ["Access Control", "Biometrics", "RFID"] },
    { id: 5, cat: "Industrial Safety", title: "ATEX Certification Explained: What Oil & Gas Companies Must Know", excerpt: "Operating in Zone 1 or Zone 2 hazardous areas demands ATEX-certified equipment. We demystify the certification process and what it means for your safety systems.", author: "Segun Afolabi", date: "Dec 28, 2024", read: "9 min", featured: false, tags: ["ATEX", "Oil & Gas", "IEC 61511"] },
    { id: 6, cat: "Industry News", title: "Nigeria's Smart City Surveillance Market: 2025 Outlook", excerpt: "Federal and state government investment in public safety infrastructure is accelerating. Here's what the data says about where the market is heading.", author: "Chukwuemeka Obi", date: "Dec 15, 2024", read: "6 min", featured: false, tags: ["Smart Cities", "Market Analysis", "Nigeria"] },
    { id: 7, cat: "Surveillance", title: "Video Analytics: Moving Beyond Basic Motion Detection", excerpt: "Modern AI-powered video analytics can recognize faces, count occupancy, detect anomalies, and trigger automated responses. Here's the practical guide.", author: "Babatunde Adewale", date: "Nov 28, 2024", read: "7 min", featured: false, tags: ["AI", "Video Analytics", "CCTV"] },
    { id: 8, cat: "ICT Infrastructure", title: "Data Center Design for Nigerian SMEs: What You Actually Need", excerpt: "You don't need a hyperscale facility. You need the right power, cooling, cabling, and network architecture for your scale — and a realistic budget to do it right.", author: "Amaka Nweze", date: "Nov 12, 2024", read: "10 min", featured: false, tags: ["Data Center", "SME", "Infrastructure"] },
];